name = "teapot-gallery"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Bind a local D1 database for development
[[d1_databases]]
binding = "DB"
database_name = "teapot-db"
database_id = "1354e189-59aa-4bbc-862d-4cde22c726cb" # We will replace this when deploying
